shell = "nu.exe"
working_directory = "C:\\Users\\jesus"

[window]
dimensions = { columns = 130, lines = 40}
padding = {x = 8, y = 0}
dynamic_title = false

[font]
normal = { family = "CaskaydiaCove Nerd Font"}
size = 12

[colors]
[colors.primary]
  background= '#181B20'
  foreground= '#abb2bf'

[colors.normal]
  black=      '#282c34'
  red=        '#ef596f'
  green=      '#89ca78'
  yellow=     '#e5c07b'
  blue=       '#61afef'
  magenta=    '#d55fde'
  cyan=       '#2bbac5'
  white=      '#abb2bf'

[colors.bright]
  black=      '#3e4451'
  red=        '#f38897'
  green=      '#a9d89d'
  yellow=     '#edd4a6'
  blue=       '#8fc6f4'
  magenta=    '#e089e7'
  cyan=       '#4bced8'
  white=      '#c8cdd5'

