{
	"$schema" : "https://aka.ms/winget-packages.schema.2.0.json",
	"CreationDate" : "2024-04-22T08:52:29.037-00:00",
	"Sources" : 
	[
		{
			"Packages" : 
			[
				{
					"PackageIdentifier" : "M2Team.NanaZip"
				},
				{
					"PackageIdentifier" : "Notion.Notion"
				},
				{
					"PackageIdentifier" : "Brave.Brave"
				},
				{
					"PackageIdentifier" : "BurntSushi.ripgrep.MSVC"
				},
				{
					"PackageIdentifier" : "Discord.Discord"
				},
				{
					"PackageIdentifier" : "Docker.DockerDesktop"
				},
				{
					"PackageIdentifier" : "Figma.Figma"
				},
				{
					"PackageIdentifier" : "Figma.FigmaAgent"
				},
				{
					"PackageIdentifier" : "Flow-Launcher.Flow-Launcher"
				},
				{
					"PackageIdentifier" : "Git.Git"
				},
				{
					"PackageIdentifier" : "HandBrake.HandBrake"
				},
				{
					"PackageIdentifier" : "Helix.Helix"
				},
				{
					"PackageIdentifier" : "JesseDuffield.lazygit"
				},
				{
					"PackageIdentifier" : "Microsoft.Edge"
				},
				{
					"PackageIdentifier" : "Microsoft.EdgeWebView2Runtime"
				},
				{
					"PackageIdentifier" : "Microsoft.AppInstaller"
				},
				{
					"PackageIdentifier" : "Microsoft.UI.Xaml.2.7"
				},
				{
					"PackageIdentifier" : "Microsoft.UI.Xaml.2.8"
				},
				{
					"PackageIdentifier" : "Microsoft.VCLibs.Desktop.14"
				},
				{
					"PackageIdentifier" : "Microsoft.DevHome"
				},
				{
					"PackageIdentifier" : "Microsoft.WindowsTerminal.Preview"
				},
				{
					"PackageIdentifier" : "Microsoft.WindowsTerminal"
				},
				{
					"PackageIdentifier" : "MongoDB.Compass.Full"
				},
				{
					"PackageIdentifier" : "Ookla.Speedtest.CLI"
				},
				{
					"PackageIdentifier" : "Postman.Postman"
				},
				{
					"PackageIdentifier" : "Rustlang.Rustup"
				},
				{
					"PackageIdentifier" : "TheBrowserCompany.Arc"
				},
				{
					"PackageIdentifier" : "Zoom.Zoom"
				},
				{
					"PackageIdentifier" : "ajeetdsouza.zoxide"
				},
				{
					"PackageIdentifier" : "Microsoft.VisualStudio.2022.Community"
				},
				{
					"PackageIdentifier" : "Obsidian.Obsidian"
				},
				{
					"PackageIdentifier" : "junegunn.fzf"
				},
				{
					"PackageIdentifier" : "nektos.act"
				},
				{
					"PackageIdentifier" : "qBittorrent.qBittorrent"
				},
				{
					"PackageIdentifier" : "Python.Python.3.11"
				},
				{
					"PackageIdentifier" : "Microsoft.VCRedist.2013.x64"
				},
				{
					"PackageIdentifier" : "Microsoft.DotNet.AspNetCore.7"
				},
				{
					"PackageIdentifier" : "LGUG2Z.komorebi"
				},
				{
					"PackageIdentifier" : "Alacritty.Alacritty"
				},
				{
					"PackageIdentifier" : "Microsoft.VCRedist.2015+.x86"
				},
				{
					"PackageIdentifier" : "Telegram.TelegramDesktop"
				},
				{
					"PackageIdentifier" : "Microsoft.DotNet.DesktopRuntime.6"
				},
				{
					"PackageIdentifier" : "Microsoft.CLRTypesSQLServer.2019"
				},
				{
					"PackageIdentifier" : "Intel.IntelDriverAndSupportAssistant"
				},
				{
					"PackageIdentifier" : "Oracle.JavaRuntimeEnvironment"
				},
				{
					"PackageIdentifier" : "Microsoft.WindowsSDK.10.0.22621"
				},
				{
					"PackageIdentifier" : "Microsoft.VisualStudioCode"
				},
				{
					"PackageIdentifier" : "Starship.Starship"
				},
				{
					"PackageIdentifier" : "Python.Launcher"
				},
				{
					"PackageIdentifier" : "Microsoft.DotNet.DesktopRuntime.7"
				},
				{
					"PackageIdentifier" : "Microsoft.VCRedist.2013.x86"
				},
				{
					"PackageIdentifier" : "OpenJS.NodeJS.LTS"
				},
				{
					"PackageIdentifier" : "Neovim.Neovim"
				},
				{
					"PackageIdentifier" : "Microsoft.PowerShell"
				},
				{
					"PackageIdentifier" : "GitHub.cli"
				},
				{
					"PackageIdentifier" : "EpicGames.EpicGamesLauncher"
				},
				{
					"PackageIdentifier" : "wez.wezterm"
				},
				{
					"PackageIdentifier" : "Nushell.Nushell"
				},
				{
					"PackageIdentifier" : "SlackTechnologies.Slack"
				},
				{
					"PackageIdentifier" : "Microsoft.XNARedist"
				},
				{
					"PackageIdentifier" : "LGUG2Z.whkd"
				},
				{
					"PackageIdentifier" : "Microsoft.VCRedist.2015+.x64"
				}
			],
			"SourceDetails" : 
			{
				"Argument" : "https://cdn.winget.microsoft.com/cache",
				"Identifier" : "Microsoft.Winget.Source_8wekyb3d8bbwe",
				"Name" : "winget",
				"Type" : "Microsoft.PreIndexed.Package"
			}
		},
		{
			"Packages" : 
			[
				{
					"PackageIdentifier" : "XPDCFJDKLZJLP8"
				}
			],
			"SourceDetails" : 
			{
				"Argument" : "https://storeedgefd.dsx.mp.microsoft.com/v9.0",
				"Identifier" : "StoreEdgeFD",
				"Name" : "msstore",
				"Type" : "Microsoft.Rest"
			}
		}
	],
	"WinGetVersion" : "1.7.10861"
}